- name: Configure cart component 
  hosts: cart
  become: yes 
  tasks: 
  - name: disable default node js 
    command: dnf module disable nodejs -y
  
  - name: enable node js:20
    command: dnf module enable nodejs:20 -y

  - name: Install NodeJS
    dnf: 
      name: nodejs
      state: installed
  
  - name: Create roboshop system cart 
    user: 
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app

  - name: Create app directory 
    file: 
      path: /app 
      state: directory

  - name: Download the cart code 
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip
    
 # This module thinks file exist on ansible control server, need to extract on to remote machine 
  - name: Extract cart code 
    unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes  # File already exist in catalogue server 

  - name: Install dependencies 
    community.general.npm:
      path: /app

  - name: copy cart service to system directory
    copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: systemctl daemon reload
    systemd_service:
      daemon_reload: true
  
  - name: Start and enable cart
    service: 
      name: cart
      state: started
      enabled: yes
  