- name: Configure catalogue component 
  hosts: catalogue
  become: yes 
  tasks: 
  - name: disable default node js 
    command: dnf module disable nodejs -y
  
  - name: enable node js:20
    command: dnf module enable nodejs:20 -y

  - name: Install NodeJS
    dnf: 
      name: nodejs
      state: installed
  
  - name: Create roboshop system user 
    user: 
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app

  - name: Create app directory 
    file: 
      path: /app 
      state: directory

  - name: Download the catalogue code 
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
    
 # This module thinks file exist on ansible control server, need to extract on to remote machine 
  - name: Extract catalogue code 
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app
    remote_src: yes
  

