- name: Configure catalogue component 
  hosts: catalogue
  become: yes 
  tasks: 
  - name: disable default node js 
    command: dnf module disable nodejs -y
  
  - name: enable node js:20
    command: dnf module enable nodejs:20 -y

  - name: Install NodeJS
    dnf: 
      name: nodejs
      state: installed
  
  - name: Create roboshop system user 
    user: 
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app

  - name: Create app directory 
    file: 
      path: /app 
      state: directory

  - name: Download the catalogue code 
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
    
 # This module thinks file exist on ansible control server, need to extract on to remote machine 
  - name: Extract catalogue code 
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes  # File already exist in catalogue server 

  - name: Install dependencies 
    community.general.npm:
      path: /app

  - name: copy catalogue service to system directory
    copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl daemon reload
    systemd_service:
      daemon_reload: true
  
  - name: Start and enable catalogue
    service: 
      name: catalogue
      state: started
      enabled: yes
  
  - name: copy mongodb repo
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    dnf: 
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    command: mongosh --host mongodb.daws84s.cloud --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0




