- name: configuring mongodb server
  hosts: mongodb
  become: yes 
  tasks:
  - name: copy mongodb repo
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    dnf: 
      name: mongodb-org
      state: installed

  - name: Start and enable mongo db 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes