- name: configuring mongodb server
  hosts: mongodb
  become: yes 
  tasks:
  - name: copy mongodb repo
    ansbile.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    ansbile.builtin.dnf: 
      name: mongodb-org
      state: installed