- name: Configure shipping component 
  hosts: shipping
  become: yes 
  tasks:
    - name: install maven and mysql
      dnf:
        name: "{{ item }}"
        state: installed 
      loop:
        - maven
        - mysql

    - name: Install PyMySQL and cryptography
      pip:
        name: "{{ item }}"
        executable: pip3.9
      loop: 
        - cryptography
        - PyMySQL

    - name: Create a system user 
      user:
        name: roboshop
        shell: /sbin/nologin
        system: true 
        home: /app

    - name: Create app directory 
      file: 
        path: /app 
        state: directory

    - name: Download the shipping code 
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
        dest: /tmp/shipping.zip

    - name: Extract shipping code 
      unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: install maven dependencies # here we are running the command module and to run that command in a specifc folder we have chdir in args 
      command: mvn clean package
      args:
        chdir: /app 
    
    - name: rename jar file 
      command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app 
  
    - name: copy shipping service 
      copy: 
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
    
    - name: daemon reload
      systemd_service:
        daemon_reload: true

    - name: enable and start shipping service 
      service:
        name: shipping 
        state: started 
        enabled: yes
      
    # - name: connect to mysql using app user
    #   community.mysql.mysql_info:
    #     login_user: shipping
    #     login_password: RoboShop@1
    #     login_host: mysql.daws84s.cloud
    #     login_db: cities 
    
    - name: import data 
      tags:
        - import 
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.daws84s.cloud
        state: import 
        target: "{{ item }}"
      loop: 
        - /app/db/schema.sql
        - /app/db/app-user.sql 
        - /app/db/master-data.sql

# ansible-playbook -i inventory.ini -e anbile_user=ec2-user -e ansible_password=DEVOPS321 shipping.yml -t import {i.e -t i run the tag specified task from playbook}

    - name: restart shipping
      tags:
        - import
      service:
        name: shipping 
        state: restarted

